### ISSUE TITLE
Can't bundle: native library compilations fails

### ISSUE THREAD

**Issue by perrypelletier** [SciRuby/nmatrix#529] opened 2016-07-16 19:05 UTC
compiling nmatrix.cpp
g++-4.8: warning: couldn't understand kern.osversion '15.3.0
In file included from /usr/local/Cellar/gcc48/4.8.3/lib/gcc/x86_64-apple-darwin14.0.0/4.8.3/include/c++/cstdint:35:0,
                 from types.h:36,
                 from nmatrix.cpp:43:

Thanks in advance for any fix/workaround.

**Comment by mohawkjohn** [comment] 2016-07-25 14:29
@perrypelletier Try the most recent version, just pushed to Rubygems (0.2.3). It should use clang by default instead of gcc.

**Comment by mohawkjohn** [comment] 2017-05-09 16:17
Duplicate of #591; closing/

**Closed by mohawkjohn** 2017-05-09 16:17 UTC
