### ISSUE TITLE
Install fails with ruby 2.3.0 on OSX 10.11.2

### ISSUE THREAD

**Issue by holidayworking** [SciRuby/nmatrix#426] opened 2015-12-29 13:00 UTC
NMatrix fails to install with ruby 2.3.0 on OSX 10.11.2

```
$ gem install nmatrix
Fetching: backports-3.6.7.gem (100%)
Successfully installed backports-3.6.7
Fetching: packable-1.3.6.gem (100%)
Successfully installed packable-1.3.6
Fetching: nmatrix-0.2.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing nmatrix:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/Cellar/rbenv/1.0.0/versions/2.3.0/lib/ruby/gems/2.3.0/gems/nmatrix-0.2.0/ext/nmatrix
/usr/local/opt/rbenv/versions/2.3.0/bin/ruby -r ./siteconf20151229-45255-7ajcsu.rb extconf.rb
checking for apparent GNU g++ binary with C++0x/C++11 support... 4.8
using C++ standard... c++11
g++ reports version... gcc48
creating nmatrix_config.h
creating Makefile

current directory: /usr/local/Cellar/rbenv/1.0.0/versions/2.3.0/lib/ruby/gems/2.3.0/gems/nmatrix-0.2.0/ext/nmatrix
make "DESTDIR=" clean

current directory: /usr/local/Cellar/rbenv/1.0.0/versions/2.3.0/lib/ruby/gems/2.3.0/gems/nmatrix-0.2.0/ext/nmatrix
make "DESTDIR="
compiling nmatrix.cpp
g++-4.8: error: unrecognized command line option '-Wdivision-by-zero'
g++-4.8: error: unrecognized command line option '-Wextra-tokens'
make: *** [nmatrix.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/nmatrix-0.2.0 for inspection.
Results logged to /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/nmatrix-0.2.0/gem_make.out
```

**Comment by mrkn** [comment] 2016-01-06 22:52
I think your ruby was built by clang.
Check it:

```
ruby -rrbconfig -e 'puts RbConfig::MAKEFILE_CONFIG["CC"]'
```

And if your ruby was built by clang, you should use clang++ for nmatrix.
Please try github version.

**Comment by v0dro** [comment] 2016-01-14 06:38
@holidayworking could you verify if your build is passing?

**Comment by mohawkjohn** [comment] 2016-01-26 14:38
I assume this is no longer a problem and will close it. Please re-open if it arises again.

**Comment by georgeu2000** [comment] 2016-04-20 18:15
I am having this issue on Ruby 2.3.0 as well.

```
ruby -rrbconfig -e 'puts RbConfig::MAKEFILE_CONFIG["CC"]'
clang
```

> And if your ruby was built by clang, you should use clang++ for nmatrix.
Please try github version.

What do you mean "try github version"? The github version of nmatrix? How?

FWIW, no issues with 2.2.4.

**Comment by mohawkjohn** [comment] 2016-04-20 18:40
You can use the current development version as described in the README:

```
git clone https://github.com/SciRuby/nmatrix.git
cd nmatrix/
gem install bundler
bundle install
bundle exec rake compile
bundle exec rake spec
```

**Comment by georgeu2000** [comment] 2016-04-20 18:44
Got it. Thanks.

**Comment by reisner** [comment] 2016-04-21 17:51
I'm getting this error with nmatrix in my gemfile. 

    $ ruby -rrbconfig -e 'puts RbConfig::MAKEFILE_CONFIG["CC"]'
    gcc

I'm not using clang...so now what? I also tried this:

    gem 'nmatrix', :github => 'SciRuby/nmatrix'

Which didnt help.

**Comment by mrkn** [comment] 2016-04-22 01:38
@georgeu2000 how do you install ruby 2.3.0?

Also, please check the following output:

```
$ ruby -v -rrbconfig -e 'puts RbConfig::MAKEFILE_CONFIG["CXX"]'
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
clang++
```

**Comment by mrkn** [comment] 2016-04-22 01:39
@reisner tell me `ruby -v`

**Comment by reisner** [comment] 2016-04-22 17:02
$ ruby -v
    ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by georgeu2000** [comment] 2016-04-27 18:36
> @georgeu2000 how do you install ruby 2.3.0?

You can download it and install it. I suggest using rbenv. See https://github.com/rbenv/rbenv#installing-ruby-versions

**Comment by mohawkjohn** [comment] 2016-05-02 14:00
@reisner Are you still having problems or can this ticket be closed?

**Closed** 2016-05-05 15:09 UTC
Labels: bug

**Comment by gillien** [comment] 2016-05-10 10:46
I had the exact same problem than @reisner. but with the configuration below : 
```
$ ruby -v -rrbconfig -e 'puts RbConfig::MAKEFILE_CONFIG["CXX"]'
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
g++
```
I was previously using Nmatrix with ruby `2.2.4` and I did not have any problems.

I try to use the development version, as @mohawkjohn described, and it was also working. 

So to get it working on my project with the version `0.2.1`, I edited the file `/Users/../.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/x86_64-darwin15/rbconfig.rb` and replace manually the `CXX` from `g++` to `clang++`  and it works now...

I am not sure if it was a good idea to follow those steps. Would be happy to have your feedbacks.

**Comment by mrkn** [comment] 2016-05-10 10:52
@gillien How do you install your ruby?
Please check the value of CC, too.
If CC is clang, it's a wrong combination of clang and g++.

**Comment by gillien** [comment] 2016-05-10 11:13
@mrkn  ruby is installed with rvm and CC is gcc

**Comment by yegor256** [comment] 2017-01-10 07:28
@mohawkjohn the problem is still there. Tried with Ruby 2.2.2 and 2.3.3, the same result. What is the solution?

**Comment by mrkn** [comment] 2017-01-11 05:17
I'll try to make a pull-request to treat the above case.

**Comment by yegor256** [comment] 2017-01-11 12:45
@mrkn thanks, it's really a blocker!

**Comment by Shekharrajak** [comment] 2017-01-28 05:13
I am getting same problem during installation. Any one found solution for this : 

```
compiling nmatrix.cpp
g++-4.8: error: unrecognized command line option '-Wdivision-by-zero'
g++-4.8: error: unrecognized command line option '-Wextra-tokens'
make: *** [nmatrix.o] Error 1
```

**Comment by mohawkjohn** [comment] 2017-02-03 19:24
@mrkn You seem to have an idea as to the cause of this — care to enlighten us? :P

**Comment by astudnev** [comment] 2017-03-12 20:28
Have the same issue:

bundle exec rake compile
mkdir -p tmp/x86_64-darwin16/nmatrix/2.3.3
cd tmp/x86_64-darwin16/nmatrix/2.3.3
/Users/studnev/.rvm/rubies/ruby-2.3.3/bin/ruby -I. ../../../../ext/nmatrix/extconf.rb
checking for apparent GNU g++ binary with C++0x/C++11 support... 4.9
using C++ standard... c++11
g++ reports version... gcc49
checking for rb_array_const_ptr() in ruby.h... yes
checking for FIX_CONST_VALUE_PTR in ruby.h... yes
checking for RARRAY_CONST_PTR in ruby.h... yes
checking for RARRAY_AREF in ruby.h... yes
creating nmatrix_config.h
creating Makefile
cd -
cd tmp/x86_64-darwin16/nmatrix/2.3.3
/usr/bin/make
compiling ../../../../ext/nmatrix/nmatrix.cpp
g++-4.9: error: unrecognized command line option '-Wdivision-by-zero'
g++-4.9: error: unrecognized command line option '-Wextra-tokens'
make: *** [nmatrix.o] Error 1
rake aborted!
Command failed with status (2): [/usr/bin/make...]
/Users/studnev/.rvm/gems/ruby-2.3.3/gems/rake-compiler-0.9.9/lib/rake/extensiontask.rb:157:in `block (2 levels) in define_compile_tasks'
/Users/studnev/.rvm/gems/ruby-2.3.3/gems/rake-compiler-0.9.9/lib/rake/extensiontask.rb:156:in `block in define_compile_tasks'
/Users/studnev/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/Users/studnev/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => compile => compile:x86_64-darwin16 => compile:nmatrix:x86_64-darwin16 => copy:nmatrix:x86_64-darwin16:2.3.3 => tmp/x86_64-darwin16/nmatrix/2.3.3/nmatrix.bundle
(See full trace by running task with --trace)

**Comment by mohawkjohn** [comment] 2017-03-13 18:17
@astudnev Try with rbenv instead of rvm. There's a post about this in the Google Group.

**Comment by achung-miovision** [comment] 2017-03-29 15:34
@Shekharrajak @astudnev Were you able to resolve the issue? I'm having the same installation errors as you on ruby 2.4.1. 

```
$ ruby -v -rrbconfig -e 'puts RbConfig::MAKEFILE_CONFIG["CXX"]'
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
g++
$ ruby -v -rrbconfig -e 'puts RbConfig::MAKEFILE_CONFIG["CC"]'
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
gcc
$  ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
```

**Comment by Shekharrajak** [comment] 2017-03-29 15:55
@achung-miovision , I uninstalled the `rvm` and now using `rbenv`. So I followed all the steps again  and it is working fine now.

**Comment by astudnev** [comment] 2017-03-30 05:38
@achung-miovision, i switched to python for this project :)

**Comment by mrkn** [comment] 2017-03-31 01:26
@achung-miovision Why do you use gcc/g++ instead of clang/clang++ on OSX?

**Comment by achung-miovision** [comment] 2017-03-31 18:51
@mrkn That seemed to be the default on my system when I installed ruby a while ago. I was able to get my issue resolved by updating rvm, then reinstalling ruby with rvm install 2.4.1 --with-cc=clang --with-cxx=clang++`.

Thanks for the help.

**Comment by sivagollapalli** [comment] 2017-04-20 12:03
@achung-miovision thanks it worked.

**Comment by zixu-zhao** [comment] 2019-01-16 19:41
@achung-miovision Thanks Adrian! You made my day! 😄

**Comment by santigolucass** [comment] 2022-01-06 02:24
@achung-miovision Thanks man!
