### ISSUE TITLE
Install fails on Linux (archlinux, gcc 5.3.0, glibc 2.22, ruby-2.3.0)

### ISSUE THREAD

**Issue by Try2Code** [SciRuby/nmatrix#429] opened 2016-01-05 09:11 UTC
Unfortunately I cannot install nmatrix on my 64bit linux box. The error message looks like this:

```
~/src/external/nmatrix bundle exec rake compile
cd tmp/x86_64-linux/nmatrix/2.3.0
make
compiling ../../../../ext/nmatrix/nmatrix.cpp
In file included from ../../../../ext/nmatrix/nmatrix.cpp:283:0:
../../../../ext/nmatrix/ruby_nmatrix.c: In function ‘VALUE nm_reshape_bang(VALUE, VALUE)’:
../../../../ext/nmatrix/ruby_nmatrix.c:1102:11: warning: unused variable ‘elem’ [-Wunused-variable]
     void* elem = s->elements;
           ^
In file included from /usr/include/ruby-2.3.0/ruby.h:33:0,
                 from ../../../../ext/nmatrix/nmatrix.cpp:34:
../../../../ext/nmatrix/ruby_nmatrix.c: In function ‘nm::dtype_t nm_dtype_guess(VALUE)’:
/usr/include/ruby-2.3.0/ruby/ruby.h:882:52: error: ‘__builtin_choose_expr’ was not declared in this scope
      OBJ_WB_UNPROTECT((VALUE)(obj)), ((VALUE)(obj))))
                                                    ^
/usr/include/ruby-2.3.0/ruby/ruby.h:1039:48: note: in definition of macro ‘RARRAY_CONST_PTR’
 #define RARRAY_CONST_PTR(a) rb_array_const_ptr(a)
                                                ^
/usr/include/ruby-2.3.0/ruby/ruby.h:1059:50: note: in expansion of macro ‘RB_OBJ_WB_UNPROTECT_FOR’
 #define RARRAY_PTR(a) ((VALUE *)RARRAY_CONST_PTR(RB_OBJ_WB_UNPROTECT_FOR(ARRAY, a)))
                                                  ^
../../../../ext/nmatrix/ruby_nmatrix.c:2639:27: note: in expansion of macro ‘RARRAY_PTR’
     return nm_dtype_guess(RARRAY_PTR(v)[0]);
                           ^
../../../../ext/nmatrix/ruby_nmatrix.c: In function ‘void* interpret_initial_value(VALUE, nm::dtype_t)’:
/usr/include/ruby-2.3.0/ruby/ruby.h:882:52: error: ‘__builtin_choose_expr’ was not declared in this scope
      OBJ_WB_UNPROTECT((VALUE)(obj)), ((VALUE)(obj))))
                                                    ^
/usr/include/ruby-2.3.0/ruby/ruby.h:1039:48: note: in definition of macro ‘RARRAY_CONST_PTR’
 #define RARRAY_CONST_PTR(a) rb_array_const_ptr(a)
                                                ^
/usr/include/ruby-2.3.0/ruby/ruby.h:1059:50: note: in expansion of macro ‘RB_OBJ_WB_UNPROTECT_FOR’
 #define RARRAY_PTR(a) ((VALUE *)RARRAY_CONST_PTR(RB_OBJ_WB_UNPROTECT_FOR(ARRAY, a)))
                                                  ^
../../../../ext/nmatrix/ruby_nmatrix.c:2801:23: note: in expansion of macro ‘RARRAY_PTR’
       rubyval_to_cval(RARRAY_PTR(arg)[index], dtype, (char*)init_val + (index * DTYPE_SIZES[dtype]));
                       ^
../../../../ext/nmatrix/ruby_nmatrix.c: In function ‘size_t* interpret_shape(VALUE, size_t*)’:
/usr/include/ruby-2.3.0/ruby/ruby.h:882:52: error: ‘__builtin_choose_expr’ was not declared in this scope
      OBJ_WB_UNPROTECT((VALUE)(obj)), ((VALUE)(obj))))
                                                    ^
/usr/include/ruby-2.3.0/ruby/ruby.h:691:51: note: in definition of macro ‘RB_FIX2UINT’
 #define RB_FIX2UINT(x) ((unsigned int)rb_fix2uint(x))
                                                   ^
../../../../ext/nmatrix/ruby_nmatrix.c:2828:22: note: in expansion of macro ‘FIX2UINT’
       shape[index] = FIX2UINT( RARRAY_PTR(arg)[index] );
                      ^
/usr/include/ruby-2.3.0/ruby/ruby.h:1059:33: note: in expansion of macro ‘RARRAY_CONST_PTR’
 #define RARRAY_PTR(a) ((VALUE *)RARRAY_CONST_PTR(RB_OBJ_WB_UNPROTECT_FOR(ARRAY, a)))
                                 ^
/usr/include/ruby-2.3.0/ruby/ruby.h:1059:50: note: in expansion of macro ‘RB_OBJ_WB_UNPROTECT_FOR’
 #define RARRAY_PTR(a) ((VALUE *)RARRAY_CONST_PTR(RB_OBJ_WB_UNPROTECT_FOR(ARRAY, a)))
                                                  ^
../../../../ext/nmatrix/ruby_nmatrix.c:2828:32: note: in expansion of macro ‘RARRAY_PTR’
       shape[index] = FIX2UINT( RARRAY_PTR(arg)[index] );
                                ^
Makefile:239: recipe for target 'nmatrix.o' failed
make: *** [nmatrix.o] Error 1
rake aborted!
Command failed with status (2): [make...]
/home/ram/.gem/ruby/2.3.0/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:155:in `block (2 levels) in define_compile_tasks'
/home/ram/.gem/ruby/2.3.0/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:154:in `block in define_compile_tasks'
Tasks: TOP => compile => compile:x86_64-linux => compile:nmatrix:x86_64-linux => copy:nmatrix:x86_64-linux:2.3.0 => tmp/x86_64-linux/nmatrix/2.3.0/nmatrix.so
(See full trace by running task with --trace)
```

**Comment by Try2Code** [comment] 2016-01-05 09:15
btw.: the makro definition is present

```
/usr/include/ruby-2.3.0 ag builtin_choose_expr                                         [10:14:33|16-01-05]
ruby/st.h
62:#if defined(HAVE_BUILTIN___BUILTIN_CHOOSE_EXPR) && defined(HAVE_BUILTIN___BUILTIN_TYPES_COMPATIBLE_P)
64:   __builtin_choose_expr(__builtin_types_compatible_p(type, st_data_t), 1, 0)

x86_64-linux/ruby/config.h
324:#define HAVE_BUILTIN___BUILTIN_CHOOSE_EXPR 1
325:#define HAVE_BUILTIN___BUILTIN_CHOOSE_EXPR_CONSTANT_P 1

ruby/ruby.h
623:#if defined(HAVE_BUILTIN___BUILTIN_CHOOSE_EXPR_CONSTANT_P)
626:	__builtin_choose_expr(\
630:    __extension__(__builtin_choose_expr(RUBY_SAFE_LEVEL_INVALID_P(level), ruby_safe_level_2_##type(), (level)))
632:/* in gcc 4.8 or earlier, __builtin_choose_expr() does not consider
877:#if defined(HAVE_BUILTIN___BUILTIN_CHOOSE_EXPR_CONSTANT_P)
880:	__builtin_choose_expr( \
1368:#if defined(HAVE_BUILTIN___BUILTIN_CHOOSE_EXPR_CONSTANT_P)
1379:#if defined(HAVE_BUILTIN___BUILTIN_CHOOSE_EXPR_CONSTANT_P)
1382:	__builtin_choose_expr( \
```

**Comment by v0dro** [comment] 2016-01-05 17:43
Strange. Does it compile with ruby 2.2?

**Comment by wlevine** [comment] 2016-01-05 21:27
I can reproduce this on Ubuntu. It's definitely a ruby 2.3 thing, works fine with ruby 2.2. Not sure if this is the same as #426

**Comment by Try2Code** [comment] 2016-01-06 08:00
Could verify successful build with 2.2.  ruby-2.1, 2.0 and 1.9 work, too

**Comment by rounak123** [comment] 2016-01-06 08:49
I m also getting these same errors!! What should i Do to remove these errors? 

compiling ../../../../ext/nmatrix/nmatrix.cpp
In file included from ../../../../ext/nmatrix/nmatrix.cpp:283:0:
../../../../ext/nmatrix/ruby_nmatrix.c: In function ‘VALUE nm_reshape_bang(VALUE, VALUE)’:
../../../../ext/nmatrix/ruby_nmatrix.c:1102:11: warning: unused variable ‘elem’ [-Wunused-variable]
     void* elem = s->elements;
           ^
../../../../ext/nmatrix/ruby_nmatrix.c: In function ‘VALUE nm_mset(int, VALUE*, VALUE)’:
../../../../ext/nmatrix/ruby_nmatrix.c:2013:109: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Wformat=]
     rb_raise(rb_eArgError, "wrong number of arguments (%d for %lu)", argc, effective_dim(NM_STORAGE(self))+1);
                                                                                                             ^
../../../../ext/nmatrix/ruby_nmatrix.c: In function ‘VALUE nm_xslice(int, VALUE*, void* (*)(const STORAGE*, SLICE*), void (*)(NMATRIX*), VALUE)’:
../../../../ext/nmatrix/ruby_nmatrix.c:2251:92: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Wformat=]
     rb_raise(rb_eArgError, "wrong number of arguments (%d for %lu)", argc, effective_dim(s));
                                                                                            ^
../../../../ext/nmatrix/ruby_nmatrix.c: In function ‘SLICE* get_slice(size_t, int, VALUE*, size_t*)’:
../../../../ext/nmatrix/ruby_nmatrix.c:2729:106: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t {aka unsigned int}’ [-Wformat=]
       rb_raise(rb_eRangeError, "slice is larger than matrix in dimension %lu (slice component %lu)", r, t);
                                                                                                          ^
../../../../ext/nmatrix/ruby_nmatrix.c:2729:106: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Wformat=]
In file included from /home/rounak/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby.h:33:0,
                 from ../../../../ext/nmatrix/nmatrix.cpp:34:
../../../../ext/nmatrix/ruby_nmatrix.c: In function ‘void* interpret_initial_value(VALUE, nm::dtype_t)’:
/home/rounak/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/ruby.h:902:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
      RARRAY(a)->as.heap.len)
                            ^
../../../../ext/nmatrix/ruby_nmatrix.c:2800:29: note: in expansion of macro ‘RARRAY_LEN’
     for (index = 0; index < RARRAY_LEN(arg); ++index) {
                             ^
In file included from ../../../../ext/nmatrix/nmatrix.cpp:283:0:
../../../../ext/nmatrix/ruby_nmatrix.c: In function ‘VALUE nm_init_new_version(int, VALUE*, VALUE)’:
../../../../ext/nmatrix/ruby_nmatrix.c:1299:60: warning: ‘init’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     nm_unregister_values(reinterpret_cast<VALUE*>(init), 1);
                                                            ^

**Comment by rounak123** [comment] 2016-01-06 08:53
Along with these errors , I m also getting many warnings!! I know warnings won't affect the code but still :( 

compiling ../../../../ext/nmatrix/storage/yale/yale.cpp
../../../../ext/nmatrix/storage/yale/yale.cpp: In function ‘void nm_init_yale_functions()’:
../../../../ext/nmatrix/storage/yale/yale.cpp:1157:136: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘unsigned int’ [-Wformat=]
     rb_raise(rb_eStandardError, "unhandled length for sizeof(IType): %lu; note that IType is probably defined as size_t", sizeof(IType));
                                                                                                                                        ^
../../../../ext/nmatrix/storage/yale/yale.cpp: In function ‘VALUE nm_nd_row(int, VALUE*, VALUE)’:
../../../../ext/nmatrix/storage/yale/yale.cpp:1911:73: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t {aka unsigned int}’ [-Wformat=]
     rb_raise(rb_eRangeError, "out of range (%lu >= %lu)", i, s->shape[0]);
                                                                         ^
../../../../ext/nmatrix/storage/yale/yale.cpp:1911:73: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Wformat=]
../../../../ext/nmatrix/storage/yale/yale.cpp: In function ‘VALUE nm_vector_set(int, VALUE*, VALUE)’:
../../../../ext/nmatrix/storage/yale/yale.cpp:1994:104: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t {aka unsigned int}’ [-Wformat=]
     rb_raise(rb_eArgError, "lengths must match between j array (%lu) and value array (%lu)", len, vvlen);
                                                                                                        ^
../../../../ext/nmatrix/storage/yale/yale.cpp:1994:104: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Wformat=]
../../../../ext/nmatrix/storage/yale/yale.cpp: In instantiation of ‘char nm::yale_storage::vector_insert(YALE_STORAGE*, size_t, size_t*, void*, size_t, bool) [with DType = unsigned char; size_t = unsigned int]’:
../../../../ext/nmatrix/storage/yale/yale.cpp:1261:3:   required from here
../../../../ext/nmatrix/storage/yale/yale.cpp:574:127: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t {aka unsigned int}’ [-Wformat=]
     rb_raise(rb_eArgError, "vector insert pos (%lu) is before beginning of ja (%lu); this should not happen", pos, s->shape[0]);
                                                                                                                               ^
../../../../ext/nmatrix/storage/yale/yale.cpp:574:127: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Wformat=]
../../../../ext/nmatrix/storage/yale/yale.cpp: In instantiation of ‘char nm::yale_storage::vector_insert(YALE_STORAGE*, size_t, size_t*, void*, size_t, bool) [with DType = signed char; size_t = unsigned int]’:
../../../../ext/nmatrix/storage/yale/yale.cpp:1261:3:   required from here
../../../../ext/nmatrix/storage/yale/yale.cpp:574:127: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t {aka unsigned int}’ [-Wformat=]
../../../../ext/nmatrix/storage/yale/yale.cpp:574:127: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Wformat=]
../../../../ext/nmatrix/storage/yale/yale.cpp: In instantiation of ‘char nm::yale_storage::vector_insert(YALE_STORAGE*, size_t, size_t*, void*, size_t, bool) [with DType = short int; size_t = unsigned int]’:
../../../../ext/nmatrix/storage/yale/yale.cpp:1261:3:   required from here
../../../../ext/nmatrix/storage/yale/yale.cpp:574:127: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t {aka unsigned int}’ [-Wformat=]
../../../../ext/nmatrix/storage/yale/yale.cpp:574:127: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Wformat=]

**Comment by v0dro** [comment] 2016-01-06 15:17
@wlevine [here](https://github.com/ruby/ruby/blame/trunk/include/ruby/ruby.h#L877) is where that macro is defined. It seems to be [newly added](https://github.com/ruby/ruby/commit/334710c155ad19cfd947ce6bcd7127b97cbe37da).

Do you think its because of the `HAVE_BUILTIN___BUILTIN_CHOOSE_EXPR_CONSTANT_P` expression?

**Comment by v0dro** [comment] 2016-01-06 15:24
Yes! Thats the problem!

Here's what I did the `nmatrix.h` file:

``` C

#include<ruby.h>
#undef RB_OBJ_WB_UNPROTECT_FOR
#define RB_OBJ_WB_UNPROTECT_FOR(type, obj) \
  (RGENGC_WB_PROTECTED_##type ? \
  OBJ_WB_UNPROTECT((VALUE)(obj)) : ((VALUE)(obj)))
```

I think there can be a cleaner fix for this. Any ideas?

Also I think we should report this as a Ruby error. Thoughts?

**Comment by v0dro** [comment] 2016-01-06 15:46
@wlevine please review my PR and see if the fix I've implemented is alright. I have a hunch that there can be a better way to fix that.

I'll document the macros that I've added once you're OK with it.

**Comment by v0dro** [comment] 2016-01-06 15:59
Looking at the [GCC docs](https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html) (scroll to `__builtin_choose_expr`), I think this is a result of using a C++ compiler.

**Comment by wlevine** [comment] 2016-01-06 17:31
@v0dro You are right, this is a C vs C++ issue. I think the best way to deal with it is just by undefining HAVE_BUILTIN___BUILTIN_CHOOSE_EXPR_CONSTANT_P before including ruby.h. Probably the best place to put this is in the nmatrix_config.h file that gets created by extconf.rb

**Comment by v0dro** [comment] 2016-01-06 17:43
I did that but it didn't work. So I went ahead and redefined that macro.

**Comment by mrkn** [comment] 2016-01-06 22:49
I think the cause of this issue is gcc's version mismatch.
I want to know gcc versions for building ruby and building nmatrix.

**Comment by wlevine** [comment] 2016-01-07 01:00
@v0dro You're right, that won't work. Another project seems to have run into the same issue and taken a different approach: https://github.com/robinst/taglib-ruby/pull/68 . Looks a little cleaner to me.

**Comment by wlevine** [comment] 2016-01-07 01:01
@mrkn It's not a gcc version mismatch. I built ruby and nmatrix with the same gcc (5.2.1)

**Comment by mrkn** [comment] 2016-01-07 06:02
@wlevine oh, I'm sorry.

But I probably found true cause of this problem.
Using RARRAY_PTR is it.  Instead, RARRAY_AREF should be used.

I'm making pull-request to fix it now.

**Comment by v0dro** [comment] 2016-01-07 07:10
I think they will fix it in the new Ruby. The bug I filed has been assigned to nobu: https://bugs.ruby-lang.org/issues/11962

**Comment by mrkn** [comment] 2016-01-07 07:27
I want to let you know that RARRAY_PTR is totally deprecated way to access to items in an array.
The new convention on the era of RGenGC is RARRAY_AREF to read and RARRAY_ASET to write into an array.
Please remember them.

**Comment by v0dro** [comment] 2016-01-07 07:31
Ok cool. That should fix it then.

**Closed** 2016-01-08 15:42 UTC
Labels: bug

**Comment by Try2Code** [comment] 2016-01-12 22:30
Thanks for your help, guys
