### ISSUE TITLE
#det and #det_exact disagree

### ISSUE THREAD

**Issue by agisga** [SciRuby/nmatrix#368] opened 2015-05-27 15:24 UTC
When working with NMatrix today, I noticed the following strange behaviour:

```Ruby
m = NMatrix.new([2,2], [1,2,3,4])  # =>[  [1, 2]   [3, 4] ]
m.det             # => 2
m.det_exact   # => -2
```

The correct determinant should be -2, as computed by `#det_exact` but not by `#det`. Am I missing something here?

**Comment by mohawkjohn** [comment] 2015-05-27 16:48
Oy. Definitely a bug. #334, #347 may be related.

**Comment by wlevine** [comment] 2015-05-29 20:02
det calls getrf, so I suspect this might be due to #360

**Comment by mohawkjohn** [comment] 2015-05-29 20:05
Oops. In that case, I'm going to mark this as a duplicate of #360 and close it. Thanks, @wlevine.

**Comment by mohawkjohn** [comment] 2015-06-08 17:05
Fixed by #370

**Closed by mohawkjohn** 2015-06-08 17:05 UTC
Labels: bug, duplicate, skill: beginner, skill: C/C++
